project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!materials-pool/"
    - "!course/"
    - "!standards/"
    - "!resources/"
    - "!.cursor/"
    - "!.claude/"
    - "!quarto/"
    - "01_organisation-introduction/01_organisation-introduction.qmd"
    - "02_self-management-notes/02_self-management-notes.qmd"
    - "03_research-questions-hypotheses/03_research-questions-hypotheses.qmd"
    - "04_reference-management-reading/04_reference-management-reading.qmd"
    - "05_dictionaries/05_dictionaries.qmd"
    - "06_corpus-linguistics-theory-methods/06_corpus-linguistics-theory-methods.qmd"
    - "07_corpus-linguistics-2/07_corpus-linguistics-2.qmd"
    - "07_corpus-linguistics-2/slides.qmd"
    - "08_questionnaires-interview/questionnaires-interviews.qmd"
    - "09_reading/09_reading.qmd"
    - "10_writing/10_writing.qmd"
    - "11_analysing-data/11_analysing-data.qmd"
    - "12_wrap-up/12_wrap-up.qmd"

execute:
  enabled: false

website:
  title: "Methods in Linguistics"
  description: "Course materials for Methods in Linguistics (MethLing251)"
  
  navbar:
    title: "MethLing251"
    left:
      - text: Sessions
        menu:
          - text: "1 Organisation and Introduction"
            href: 01_organisation-introduction/01_organisation-introduction.html
          - text: "2 Self-management and Notes"
            href: 02_self-management-notes/02_self-management-notes.html
          - text: "3 Research Questions & Hypotheses"
            href: 03_research-questions-hypotheses/03_research-questions-hypotheses.html
          - text: "4 Reference management & Reading"
            href: 04_reference-management-reading/04_reference-management-reading.html
          - text: "5 Dictionaries"
            href: 05_dictionaries/05_dictionaries.html
          - text: "6 Corpus linguistics: theory and methods"
            href: 06_corpus-linguistics-theory-methods/06_corpus-linguistics-theory-methods.html
          - text: "7 Corpus Linguistics 2"
            href: 07_corpus-linguistics-2/07_corpus-linguistics-2.html
          - text: "8 Questionnaires & Interviews" 
            href: 08_questionnaires-interview/questionnaires-interviews.html
          - text: "9 Reading"
            href: 09_reading/09_reading.html
          - text: "10 Writing"
            href: 10_writing/10_writing.html
          - text: "11 Analysing Data"
            href: 11_analysing-data/11_analysing-data.html
          - text: "12 Wrap-up"
            href: 12_wrap-up/12_wrap-up.html
    
    right:
      - icon: github
        href: https://github.com/wuqui/MethLing251
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    number-sections: false
    highlight-style: github
    code-fold: true



